<?php
/**
 * Barranco Contact
 *
 * @var \Magento\Contact\Block\ContactForm $block
 * @var \Barranco\Contact\ViewModel\ContactForm $viewModel
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$viewModel = $block->getViewModel();
?>
<div id="contact" data-bind="scope:'contact'" class="contact-container">
    <div class="loading-mask" data-mage-init='{"contactLoader": {}}'>
        <div class="loader">
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>" />
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#contact": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <?php
    $serializedConfig = /* @noEscape */ $viewModel->getSerializedConfig();
    $scriptString = <<<script
        window.contactConfig = {$serializedConfig};
    script;
    ?>
    <?= /* @noEscape  */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</div>
